# Generated by Django 3.2.6 on 2021-09-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_remove_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(1, 'Furniture'), (2, 'Electronics & Appliances'), (3, 'Vehicles'), (4, 'Clothings'), (5, 'Handicrafts'), (6, 'Stationary'), (7, 'Pets'), (8, 'Beauty'), (9, 'miscellaneous')], default='', max_length=50),
        ),
    ]
