# Generated by Django 3.2.6 on 2021-09-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
