# Generated by Django 3.2.6 on 2021-09-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_user_id'),
        ('Posts', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpost',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.post'),
        ),
        migrations.AlterField(
            model_name='savedpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
        ),
    ]
