# Generated by Django 3.2.6 on 2021-09-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_profile_image'),
        ('Posts', '0013_auto_20210904_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, default='', null=True)),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('answered_date', models.DateField(blank=True, default='', null=True)),
                ('answered_time', models.TimeField(blank=True, default='', null=True)),
                ('answer', models.TextField(blank=True, default='', null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
            ],
        ),
    ]
