# Generated by Django 3.2.6 on 2021-09-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20210903_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Electronics & Appliances', 'Electronics & Appliances'), ('Vehicles', 'Vehicles'), ('Clothings', 'Clothings'), ('Handicrafts', 'Handicrafts'), ('Stationary', 'Stationary'), ('Pets', 'Pets'), ('Beauty', 'Beauty'), ('miscellaneous', 'miscellaneous')], default='', max_length=50),
        ),
    ]
